# Jekyll setup for thomasburgess.github.io                                                           
# _____ _                        _____                         
#|_   _| |_ ___ _____ ___ ___   | __  |_ _ ___ ___ ___ ___ ___ 
#  | | |   | . |     | .'|_ -|  | __ -| | |  _| . | -_|_ -|_ -|
#  |_| |_|_|___|_|_|_|__,|___|  |_____|___|_| |_  |___|___|___|
#  (why are your reading this?)               |___|            

## => Site Settings
##############################

# Site settings


title   : Thomas T Burgess's Blog
email: nxpnsv+thomastburgess@gmail.com
description: > # this means to ignore newlines until "Language & timezone"
  Personal blog of particle physicist and data scientist Thomas T Burgess. 
  Here I write about math, geometric art, python coding, statistics, data science, 
  machine learning and other things I do.
baseurl: ""
url: https://thomasburgess.github.io
subtitle: Numbers, numbers - everywhere!
repository: thomasburgess/thomasburgess.github.io
github_username:  thomasburgess
timezone: Europe/Vienna

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

remote_theme: dieghernan/chulapa

footer:
  links:
    - label : Repo on Github # Label
      icon  : fab fa-github # Fontawesome 5 icon
      url   : https://github.com/thomasburgess
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"

# SEO
og_image                : https://github.com/thomasburgess.png
author:
  name                  :      Thomas T Burgess
  avatar                :      https://github.com/thomasburgess.png
  location              :      Vienna, Austria
  links:                
    - url: https://mathstodon.xyz/@ngons
      icon: "fab fa-mastodon"
      label: "@ngons@mathstodon.xyz - my mastodon social"
    - url: https://github.com/thomasburgess
      icon: "fab fa-github"
      label: "my code at github."
    - url:  nxpnsv+thomastburgess@gmail.com
      icon: far fa-envelope
      label: "My personal email"
    -  url: https://orcid.org/0000-0002-6993-5918      
       icon: "fa-brands fa-orcid"
       label: "My Orcid"

comments:
  provider: giscus         

chulapa-skin: 
  skin       :  minty
  autothemer  :  # Autotheming may not have any effect
  highlight     : dracula

plugins:
  # - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-figure

compress_html:
  clippings: all
  blanklines: true

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

navbar:
  style     :  "dual" #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  Home # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  /assets/images/favicons/favicon-96x96.png 
  nav:
  - title   : Blog # Label
    url     : /blog/ # url	
  - title : Tags
    url   : /tags
  - title : Categories
    url   : /categories
  - title : Archive
    url   : /archive

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

search:
  provider: lunr
  label: search
  landing_page: /search
  lunr_maxwords: 30

paginate: 5
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  
permalink: /:year/:month/:day/:title:output_ext


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags
      cloudcategory_url   : /categories
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      show_toc: true
      show_sidetoc: true
      breadcrumb_list:
        - label: Home
          url: /
        - label: Blog
          url: /blog

# Markdown Processing
markdown: kramdown

kramdown:
  auto_ids: true
  
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

